- name: Wait
  shell:
    cmd: sleep 20
  args:
    executable: /bin/bash

- name: Overcommit_memory warnings Fix
  lineinfile:
    path: "/etc/sysctl.conf"
    line: "vm.overcommit_memory = 1"

- name: Add Redis PPA
  ansible.builtin.apt_repository:
    repo: ppa:redislabs/redis

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Ensure installing basic dependencies
  apt:
    name:
      - redis-server
      - redis-sentinel
      - net-tools
      - curl
    state: present

- name: Enable Redis Server
  shell:
    cmd: systemctl enable redis-server
  args:
    executable: /bin/bash

- name: Check if redis installed
  shell:
    cmd: echo "PING" | redis-cli
  args:
    executable: /bin/bash

